name: Update Recent Activity

on:
  schedule:
    - cron: "30 4 * * 0"  # This will run every Sunday at 10:00 AM IST

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activities

    steps:
      - uses: actions/checkout@v3  # Updated to v3 for compatibility with Node.js 16 and 20
      - uses: jamesgeorge007/github-activity-readme@v1.1  # Specifying the latest stable version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Updated README with recent activities"
          MAX_LINES: 4
          GH_USERNAME: Suraj-kumar00
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          TARGET_FILE: README.md
          EMPTY_COMMIT_MSG: ":memo: empty commit to keep workflow active after 60 days of no activity"
