name: hashnode-card
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  hashnode-card:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: hashnode-card
        uses: hashnode/action-hashnode-card@1.0.0
        with:
          username: ${{ secrets.HASHNODE_USERNAME }}
          api_key: ${{ secrets.HASHNODE_API_KEY }}
          commit_message: "chore: update ${filename}"
