name: 'Hashnode Blogs'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0' # Runs every week on Sunday at 3:30 AM UTC (9:00 AM IST).

jobs:
  update_blogs:
    name: 'Hashnode Latest Blogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch Repository Contents'
        uses: actions/checkout@v2

      - name: 'Fetch Latest Blog Posts'
        id: fetch-posts
        uses: Sachin-chaurasiya/hashnode-blog-action@main
        with:
          HASHNODE_PUBLICATION_NAME: 'surajk00.hashnode.dev/'
          FORMAT: 'stacked limit=4'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Append Latest Blog Posts to README'
        run: |
          echo "${{ steps.fetch-posts.outputs.posts }}" >> README.md
          git add README.md
          git commit -m "Update README with latest blog posts"
          git push
