name: 'Hashnode Blogs'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every hour, on the hour.

jobs:
  update_blogs:
    name: 'Hashnode Latest Blogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch Repository Contents'
        uses: actions/checkout@main

      - name: 'Hashnode Blog Action'
        uses: "Suraj-kumar00/hashnode-blog-action@main"
        with:
          HASHNODE_PUBLICATION_NAME: 'blog.surajk00.hashnode.dev'
          FORMAT: 'stacked'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
